vim.keymap.set('n', '<C-t>', ':NERDTreeToggle<CR>', {silent = true})
vim.keymap.set('n', 'te', ':tabedit<CR>', {silent = true})
vim.keymap.set('n', 'sv', ':vsplit<CR><C-w>w', {silent = true})
vim.keymap.set('n', 'ss', ':split<CR><C-w>w', {silent = true})
vim.keymap.set('n', '=', '<C-a>')
vim.keymap.set('n', '-', '<C-x>')
vim.keymap.set('n', 't<left>', ':tabprev<CR>', {silent = true})
vim.keymap.set('n', 't<right>', ':tabnext<CR>', {silent = true})
vim.keymap.set('n', 'th', ':tabprev<CR>', {silent = true})
vim.keymap.set('n', 'tl', ':tabnext<CR>', {silent = true})
vim.keymap.set('n', '<C-a>', 'a <ESC>r', {silent = true})
vim.keymap.set('v', '<tab>', '>')
vim.keymap.set('v', '<s-tab>', '<')

