#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset b off &
xset r rate 250 &
kbdd &
/usr/games/buckle -g 15 > /dev/null 2> /dev/null &

bash ~/Documents/res.sh &
polybar &
dunst &
nitrogen --restore &

#export PATH=$PATH:$HOME/.local/bin

/home/danilus/.local/bin/picom -b --config="/home/danilus/.config/picom/picom.conf" --experimental-backends --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 500

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config normal_border_color  "#fca6d5"
bspc config focused_border_color "#ff44ab"
bspc config border_width         2
bspc config window_gap           5

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop=^2
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Firefox-esr desktop=^4

discord &
telegram-desktop &
firefox-ers &

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
